### ISSUE TITLE
Add possibility to not register line numbers

### ISSUE THREAD

**Issue by gorkat** [laget-se/react-gettext-parser#25]
Hello,

I would like to know if you would consider to add an option allowing us to deactivate line numbers in .pot files?

In fact, the .pot files are looking like this `<filename>.jsx:45`. The problem is that, when you do add/modify/remove some localized strings in your code, react-gettext-parser will update those line numbers. As a result our commits are very big and it is painful to get your code reviewed (because lot of LOCs) ;)

Thanks in advance!

**Comment by alexanderwallin** [comment]
Hi @gorkat!

That does sound annoying. Is it necessary for you to source control the .pot file? Since it is a direct derivative output from your JavaScript source code, you could perhaps just run `react-gettext-parser` when you need it?

**Comment by gorkat** [comment]
Hey,

Yes you are right, `.pot` files should not be source controlled. But in our case, we are used to provide them with our source code to prevent non-tech people to deal with IT stuff. It can be an actual achievement for some people to use poedit, so imagine a second running some command from a CLI ;)

Moreover, when you create your `.po` files from your `.pot` files (PoEdit), line numbers are still referenced and updated when you modify your source code.

What do you think about it?

**Comment by alexanderwallin** [comment]
Hehe, yeah we shouldn't burden the unwilling non-techies with the terminal. One solution could be to write a simple script that uploads the .pot to a server (i.e. internal or Dropbox) whenever `master` updates.

It's definitely possible to implement this feature, but it does defeat one of the main appeals with this package; it lets your JavaScript code be the single source of truth.

If we added this feature, you would still get ugly diffs if you rename files or folders. Even if we omit the source file paths entirely from the .pot, translation blocks inside it would be reordered if a renamed file makes it change position in the file listing (strings from `A.js` will come before strings from `B.js` in the outputted .pot file).

**Comment by gorkat** [comment]
You are right, but it is not very usual to rename files or folders unless you are doing some refactoring, which is, to my point of view totally acceptable in this case.

My idea was not to remove totally blocks references, that would be kind of stupid, but to add an option like `--no-line-numbers`. For instance, the package we use for angular `angular-gettext` provides this kind of option. But anyway, you are the decider, I won't argue more if you think this is bad :)

However, if you change of mind, I can contribute by making a pull request, just let me know ;)

**Comment by gorkat** [comment]
Finally I understood what you meant: without line numbers blocks are still reordered in function of the place strings appears in files. This comes from the fact that the parser doesn't check the existence of blocks in the .pot and entirely rewrite it instead of doing a merge. Deactivating line numbers is something easy but you would have to write another mountain of code just to parse your `.pot` file and merging it with the new found blocks.

I think you can close this issue, thanks for your answers :)

**Comment by Sequoia** [comment]
Oh darn. I definitely still would appreciate this feature, for the same reason (huge diffs if I add an extra `import` to the top of a file with `gettext` calls). I see the value in having line number reference comments, but the value is in our case definitely not outweighed by the drawbacks. If I need to know where a string is used, I can still `grep` it in a pinch, which is is much less pain in our use case than a single line addition resulting in large diffs with tons of line changes.

We also track our `.pot` file because it's a combination of strings from a React & an Angular app, and we don't want to be "up a creek" if our extract/compile process stops working. We also track so we can notice major problems, e.g. an extractor utility failing that causes a large portion of the `.pot` to disappear. We had this problem in fact, and because we would extract & push directly to translators (without a diff to review) we completely missed it, so we're adding the `.pot` file back to tracking, which leaves us with the line number issue again 😅 

I'll try to submit a PR to make this an *option* (haven't looked into it at all yet).

**Comment by alexanderwallin** [comment]
Thanks for providing such a detailed use case, @Sequoia. I'll merge your PR and publish a new version!
